name: Warren Workshop VI 2016
description: Warren Workshop VI 2016
url: http:/yamazakim.github.io/WarrenWorkshop2016
#exclude: [deprecated]
exclude: ['vendor']
safe: true
highlighter: pygments
markdown: redcarpet
paginate: 2
paginate_path: "/blog/page:num/"
permalink: pretty
#permalink: :categories/:title
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data', 'superscript']
gems: [jekyll-paginate]
